name: tests and lint

# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      - run: runingTest
